// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'fadeInAn': string;
  'fadeOut': string;
  'fadeOutAn': string;
  'fadein': string;
  'header': string;
  'header__button': string;
  'header__intro': string;
  'header__link': string;
  'header__title': string;
  'link': string;
  'mb-hg': string;
  'mb-lg': string;
  'mb-md': string;
  'mb-sm': string;
  'moveBackTop': string;
  'moveInLeft': string;
  'moveInRight': string;
  'moveInRightAn': string;
  'moveInRotateTop': string;
  'moveInTop': string;
  'openIn': string;
  'project': string;
  'project__title': string;
  'projects': string;
  'projects__image': string;
  'projects__item': string;
  'projects__items': string;
  'projects__link': string;
  'u-center-text': string;
  'wiggle': string;
  'wiggleAn': string;
}
export const cssExports: CssExports;
export default cssExports;
