// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'fadein': string;
  'header': string;
  'header__heading': string;
  'header__heading-sub': string;
  'header__title': string;
  'home': string;
  'home__main': string;
  'home__title': string;
  'mb-hg': string;
  'mb-lg': string;
  'mb-md': string;
  'mb-sm': string;
  'moveInLeft': string;
  'moveInRight': string;
  'overview': string;
  'overview__about': string;
  'overview__btn': string;
  'overview__image': string;
  'overview__info': string;
  'overview__name': string;
  'overview__type': string;
  'overviews': string;
  'projects': string;
  'projects__content': string;
  'projects__heading': string;
  'projects__heading--sub': string;
  'projects__image': string;
  'projects__image-1': string;
  'projects__image-2': string;
  'projects__pictures': string;
  'title': string;
  'type': string;
  'type1': string;
  'u-center-text': string;
  'wiggle': string;
}
export const cssExports: CssExports;
export default cssExports;
