// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about': string;
  'about__item': string;
  'about__items': string;
  'about__text': string;
  'about__title': string;
  'background': string;
  'btn': string;
  'detail': string;
  'detail__text': string;
  'fadeInAn': string;
  'fadeOut': string;
  'fadeOutAn': string;
  'fadein': string;
  'header': string;
  'header__title': string;
  'link': string;
  'mb-hg': string;
  'mb-lg': string;
  'mb-md': string;
  'mb-sm': string;
  'moveBackTop': string;
  'moveInLeft': string;
  'moveInRight': string;
  'moveInRightAn': string;
  'moveInRotateTop': string;
  'moveInTop': string;
  'openIn': string;
  'project': string;
  'u-center-text': string;
  'wiggle': string;
  'wiggleAn': string;
}
export const cssExports: CssExports;
export default cssExports;
