// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'fadein': string;
  'mb-hg': string;
  'mb-lg': string;
  'mb-md': string;
  'mb-sm': string;
  'moveInLeft': string;
  'moveInRight': string;
  'nav': string;
  'nav__item': string;
  'nav__item-brand': string;
  'nav__items': string;
  'nav__link': string;
  'nav__link-brand': string;
  'u-center-text': string;
  'wiggle': string;
}
export const cssExports: CssExports;
export default cssExports;
