// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'btn': string;
  'fadein': string;
  'layout__container': string;
  'layout__content': string;
  'layout__navigation': string;
  'mb-hg': string;
  'mb-lg': string;
  'mb-md': string;
  'mb-sm': string;
  'moveInLeft': string;
  'moveInRight': string;
  'u-center-text': string;
  'wiggle': string;
}
export const cssExports: CssExports;
export default cssExports;
