// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'copyright': string;
  'fadein': string;
  'footer': string;
  'moveInLeft': string;
  'moveInRight': string;
  'nav': string;
  'nav__link': string;
  'u-center-text': string;
  'wiggle': string;
}
export const cssExports: CssExports;
export default cssExports;
