const FETCH_SUCCESS = "FETCH_SUCCESS";
const FETCH_FAILED = "FETCH_FAILED";
const FETCH_BY_COUNTRY_SUCCESS = "FETCH_BY_COUNTRY_SUCCESS";

export { FETCH_SUCCESS, FETCH_FAILED, FETCH_BY_COUNTRY_SUCCESS };
