// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'mb-hg': string;
  'mb-lg': string;
  'mb-md': string;
  'mb-sm': string;
}
export const cssExports: CssExports;
export default cssExports;
